spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis_plus_test?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
logging:
  level:
    root: warn
    com.ce.crud.dao: trace
  pattern:
    console: '%p %m%n'

mybatis-plus:
  mapper-locations:
    - mapper/*
#  global-config:
  #    db-config:
  #      #      table-prefix: mp_ 表名前缀
  #      # 全局 主键策略
  #      id-type: none
  #config-location: classpath:mybatis-plus.xml
  type-aliases-package: com.ce.crud.entity
  configuration:
    map-underscore-to-camel-case: true  # 默认 true